# Generated by Django 4.1.6 on 2023-02-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_is_admin_alter_myuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman')], default=1, null=True, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Insomnia'), (2, 'Diabet'), (3, 'Heart Attack'), (4, 'Being Nihad')], null=True, verbose_name='Choose your Diseases')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
