# Generated by Django 4.1.6 on 2023-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_disease_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
