# Generated by Django 4.1.6 on 2023-03-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_callhelp_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhelp',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
