# Generated by Django 4.1.6 on 2023-03-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_callhelp_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
