# Generated by Django 4.1.6 on 2023-04-05 10:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_myuser_adress_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='user',
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to='account.disease')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.userdisease'),
        ),
    ]
