# Generated by Django 4.1.6 on 2023-04-05 14:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_doctoruser_remove_disease_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorUser',
        ),
        migrations.CreateModel(
            name='UserUser',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_disease',
        ),
        migrations.AddField(
            model_name='userdisease',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Choose your Diseases'),
        ),
        migrations.AlterField(
            model_name='userdisease',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to='account.disease'),
        ),
    ]
