# Generated by Django 4.1.6 on 2023-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_doctoruser_useruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Add Photo'),
        ),
    ]
