# Generated by Django 4.1.6 on 2023-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_pp', verbose_name='image'),
        ),
    ]
